### ISSUE TITLE
MainMenu game can't be parsed

### ISSUE THREAD

**Issue by tfassbender** [tfassbender/genesis_project#7]
When loading the game in the main menu it seems that the game can't be parsed:

```
[DEBUG] 2020-01-11 11:23:09.452 [notification_listener_thread] NotifierSubscriberClient - received message: main_menu/game_started/7
[DEBUG] 2020-01-11 11:23:09.452 [notification_listener_thread] NotifierService - received notification message: main_menu/game_started/7
[DEBUG] 2020-01-11 11:23:09.455 [getGameAsync] GenesisClient - sending request to URI: http://jfabricationgames.ddns.net:5715/genesis_project_server/genesis_project/genesis_project/get_game/7 (type: GET   entity: null)
[ERROR] 2020-01-11 11:23:09.588 [JavaFX Application Thread] MainMenuController - unknown error whil loading the game
net.jfabricationgames.genesis_project.connection.exception.GenesisServerException: Parsing of the game failed
	at net.jfabricationgames.genesis_project.connection.GenesisClient.getGame(GenesisClient.java:215) ~[classes/:?]
	at net.jfabricationgames.genesis_project.connection.GenesisClient.lambda$2(GenesisClient.java:221) ~[classes/:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270) ~[jackson-databind-2.8.4.jar:2.8.4]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3838) ~[jackson-databind-2.8.4.jar:2.8.4]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783) ~[jackson-databind-2.8.4.jar:2.8.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842) ~[jackson-databind-2.8.4.jar:2.8.4]
	at net.jfabricationgames.genesis_project.connection.GenesisClient.getGame(GenesisClient.java:211) ~[classes/:?]
	... 2 more

```

**Comment by tfassbender** [comment]
mapper used wrong configuration. fixed and tested
