### ISSUE TITLE
ClassSelectionPane.fxml can't be loaded (Location not set)

### ISSUE THREAD

**Issue by tfassbender** [tfassbender/genesis_project#9]
The ClassSelectionPane can't be loaded from the PreGameSelectionController (exception says location is not set, but seems correct...)

```
[INFO ] 2020-01-11 11:21:05.821 [JavaFX Application Thread] GenesisClient - Host configuration loaded: {server.port=5715, notifier.host=jfabricationgames.ddns.net, server.host=jfabricationgames.ddns.net, notifier.port.rest=5714, notifier.port.socket=5716}
[INFO ] 2020-01-11 11:21:05.825 [JavaFX Application Thread] GameManager - GameManager started successfully
[ERROR] 2020-01-11 11:23:09.152 [JavaFX Application Thread] MainMenuController - GameFrame couldn't be loaded
javafx.fxml.LoadException: 
/C:/Users/Tobias/eclipse/workspace/GenesisProject/target/classes/net/jfabricationgames/genesis_project/game_frame/pre_game/PreGameSelectionFrame.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409) ~[jfxrt.jar:?]
	at net.jfabricationgames.genesis_project.main_menu.MainMenuController.startPreGameFrame(MainMenuController.java:434) ~[classes/:?]
	at net.jfabricationgames.genesis_project.main_menu.MainMenuController.access$6(MainMenuController.java:429) ~[classes/:?]
	at net.jfabricationgames.genesis_project.main_menu.MainMenuController$5.lambda$0(MainMenuController.java:345) ~[classes/:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_172]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.lang.IllegalStateException: Location is not set.
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2434) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409) ~[jfxrt.jar:?]
	at net.jfabricationgames.genesis_project.game_frame.util.GuiUtils.insertPane(GuiUtils.java:63) ~[classes/:?]
	at net.jfabricationgames.genesis_project.game_frame.pre_game.PreGameSelectionController.initialize(PreGameSelectionController.java:43) ~[classes/:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548) ~[jfxrt.jar:?]
	... 12 more
```

Code in PreGameSelectionController (line 43) is:
`guiUtils.insertPane("ClassSelectionPane.fxml", anchorClassSelectionPane, classSelectionController, null);`

InsertPane in GuiUtils:
```

	public void insertPane(String fxmlFileName, AnchorPane parent, Initializable controller, String cssFileName) {
		try {
			URL fxmlUrl = getClass().getResource(fxmlFileName);
			FXMLLoader fxmlLoader = new FXMLLoader(fxmlUrl);
			fxmlLoader.setController(controller);
			Parent pane = fxmlLoader.load();
			if (cssFileName != null) {
				pane.getStylesheets().add(getClass().getResource(cssFileName).toExternalForm());
			}
			parent.getChildren().add(pane);
			AnchorPane.setBottomAnchor(pane, 0d);
			AnchorPane.setTopAnchor(pane, 0d);
			AnchorPane.setLeftAnchor(pane, 0d);
			AnchorPane.setRightAnchor(pane, 0d);
		}
		catch (IOException ioe) {
			ioe.printStackTrace();
			LOGGER.error("An exception occured while inserting a pane to the main frame", ioe);
		}
	}
```

**Comment by tfassbender** [comment]
Caused by wrong load location (loader was GuiUtils in a different package). Added note in comments and added the possibility to use a specified loader object (as parameter).

This problem will probably also occure in other loaders...
